### ISSUE TITLE
Bare except block

### ISSUE THREAD

**Issue by tookiebunten** [dgplacenames/osnb#1]
A bare except catches BaseException which includes KeyboardInterrupt, SystemExit, Exception, and others. Catching BaseException can make it hard to interrupt the program (e.g., with Ctrl-C) and can disguise other problems. Full details are available here https://docs.astral.sh/ruff/rules/bare-except/

Example#

try:
    raise KeyboardInterrupt("You probably don't mean to break CTRL-C.")
except:
    print("But a bare `except` will ignore keyboard interrupts.")
Use instead:

try:
    do_something_that_might_break()
except MoreSpecificException as e:
    handle_error(e)
If you actually need to catch an unknown error, use Exception which will catch regular program errors but not important system exceptions.

def run_a_function(some_other_fn):
    try:
        some_other_fn()
    except Exception as e:
        print(f"How exceptional! {e}")

**Comment by tookiebunten** [comment]
Forgot to add a better example. Something like this 

```
def parse_placename(html):
    try:
        name = html.css("div.well")
        results = []
        for item in name:
            new_item = placename_information(
                placename=item.css_first("td").text().strip(),
                various_spellings=item.css_first("td:nth-child(2)").text().replace('\n', '').strip(),
                authority=item.css_first("td:nth-child(3)").text().strip(),
                situation=item.css_first("td:nth-child(4)").text().strip(),
                description=item.css_first("td:nth-child(5)").text().strip(),
            )
            results.append(asdict(new_item))
        return results
    except AttributeError as error:
        return results
```

**Comment by dgplacenames** [comment]
Thanks very much for this. I'll look into it.

**Comment by tookiebunten** [comment]
fixed in merge
