### ISSUE TITLE
"No image" stops the script

### ISSUE THREAD

**Issue by MrAndySweet** [dgplacenames/osnb#5]
I've encountered an issue when there is no image on a page, which stops the script from running.

e.g. There is no image or info for page 77 of volume 33 of the Aberdeenshire books.

https://scotlandsplaces.gov.uk/digital-volumes/ordnance-survey-name-books/aberdeenshire-os-name-books-1865-1871/aberdeenshire-volume-33/77

This resulted in the script stopping, with the following error message:

/aberdeenshire-volume-33/73
/aberdeenshire-volume-33/74
/aberdeenshire-volume-33/75
/aberdeenshire-volume-33/76
Traceback (most recent call last):
  File "/Users/andy/Downloads/osnb-main/county_scraper.py", line 49, in <module>
    panel_body = page_soup.find('div',{'class':'panel-body'}).get_text(' ', strip = True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_text'

**Comment by dgplacenames** [comment]
Thanks for flagging this Andy. I'll hopefully get it sorted this evening.

**Comment by dgplacenames** [comment]
Got it working my end. Let me know if you're still having trouble with it.

**Comment by MrAndySweet** [comment]
I've just scraped Volume 33 successfully, thanks.

**Comment by dgplacenames** [comment]
Excellent :)
